apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubewait-query-role
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubewait-query-sa
  namespace: default
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubewait-query-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubewait-query-role
subjects:
- kind: ServiceAccount
  name: kubewait-query-sa
  namespace: default
