apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  labels:
    app: sample-app
spec:
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      name: sample-template
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-workload
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
          - >
            echo 'Waiting for 30 seconds before starting up...' &&
            sleep 30 &&
            echo ready > /tmp/ready &&
            sleep 9999
        resources:
          limits:
            memory: 64Mi
            cpu: 25m
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - cat /tmp/ready
          periodSeconds: 5
          failureThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: sample-service
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: sample-app
